// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package burpfmt

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
	"bytes"
)

type BurpProject struct {
	Header *BurpProject_Header
	Roots *BurpProject_Roots
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject() *BurpProject {
	return &BurpProject{
	}
}

func (this BurpProject) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewBurpProject_Header()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	tmp2 := NewBurpProject_Roots()
	err = tmp2.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Roots = tmp2
	return err
}
type BurpProject_AddressArray struct {
	TotalSize int32
	ElementCount int32
	Padding []byte
	Addresses []int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject_AddressArray() *BurpProject_AddressArray {
	return &BurpProject_AddressArray{
	}
}

func (this BurpProject_AddressArray) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_AddressArray) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.TotalSize = int32(tmp3)
	tmp4, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.ElementCount = int32(tmp4)
	if (this.ElementCount == 0) {
		tmp5, err := this._io.ReadBytes(int(1))
		if err != nil {
			return err
		}
		tmp5 = tmp5
		this.Padding = tmp5
	}
	for i := 0; i < int(this.ElementCount); i++ {
		_ = i
		tmp6, err := this._io.ReadS8be()
		if err != nil {
			return err
		}
		this.Addresses = append(this.Addresses, tmp6)
	}
	return err
}

/**
 * Identity index bucket; field 0 size, field 1 hash/key/value tuples.
 */
type BurpProject_Bucket struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_size bool
	size *BurpProject_FindI32
	_f_tuplesAddr bool
	tuplesAddr *BurpProject_FindAddr
}
func NewBurpProject_Bucket(base int64) *BurpProject_Bucket {
	return &BurpProject_Bucket{
		Base: base,
	}
}

func (this BurpProject_Bucket) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_Bucket) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp7 := NewBurpProject_CompactObject(this.Base)
	err = tmp7.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp7
	return err
}
func (this *BurpProject_Bucket) Size() (v *BurpProject_FindI32, err error) {
	if (this._f_size) {
		return this.size, nil
	}
	this._f_size = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp8, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp9 := NewBurpProject_FindI32(0, this.Base, tmp8)
	err = tmp9.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.size = tmp9
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.size, nil
}
func (this *BurpProject_Bucket) TuplesAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_tuplesAddr) {
		return this.tuplesAddr, nil
	}
	this._f_tuplesAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp10, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp11 := NewBurpProject_FindAddr(1, this.Base, tmp10)
	err = tmp11.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.tuplesAddr = tmp11
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.tuplesAddr, nil
}
type BurpProject_BucketTuple struct {
	Hash int64
	KeyAddress int64
	Value int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent *BurpProject_BucketTuples
}
func NewBurpProject_BucketTuple() *BurpProject_BucketTuple {
	return &BurpProject_BucketTuple{
	}
}

func (this BurpProject_BucketTuple) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_BucketTuple) Read(io *kaitai.Stream, parent *BurpProject_BucketTuples, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp12, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.Hash = int64(tmp12)
	tmp13, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.KeyAddress = int64(tmp13)
	tmp14, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.Value = int64(tmp14)
	return err
}
type BurpProject_BucketTuples struct {
	TotalSize int32
	ElementCount int32
	Padding []byte
	Tuples []*BurpProject_BucketTuple
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject_BucketTuples() *BurpProject_BucketTuples {
	return &BurpProject_BucketTuples{
	}
}

func (this BurpProject_BucketTuples) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_BucketTuples) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp15, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.TotalSize = int32(tmp15)
	tmp16, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.ElementCount = int32(tmp16)
	if (this.ElementCount == 0) {
		tmp17, err := this._io.ReadBytes(int(1))
		if err != nil {
			return err
		}
		tmp17 = tmp17
		this.Padding = tmp17
	}
	for i := 0; i < int(this.ElementCount); i++ {
		_ = i
		tmp18 := NewBurpProject_BucketTuple()
		err = tmp18.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Tuples = append(this.Tuples, tmp18)
	}
	return err
}

/**
 * Chunk list for Zwtw chunked collections.
 */
type BurpProject_ChunkList struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_chunkArrayAddr bool
	chunkArrayAddr *BurpProject_FindAddr
	_f_chunkCount bool
	chunkCount *BurpProject_FindI32
}
func NewBurpProject_ChunkList(base int64) *BurpProject_ChunkList {
	return &BurpProject_ChunkList{
		Base: base,
	}
}

func (this BurpProject_ChunkList) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ChunkList) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp19 := NewBurpProject_CompactObject(this.Base)
	err = tmp19.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp19
	return err
}
func (this *BurpProject_ChunkList) ChunkArrayAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_chunkArrayAddr) {
		return this.chunkArrayAddr, nil
	}
	this._f_chunkArrayAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp20, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp21 := NewBurpProject_FindAddr(1, this.Base, tmp20)
	err = tmp21.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunkArrayAddr = tmp21
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunkArrayAddr, nil
}
func (this *BurpProject_ChunkList) ChunkCount() (v *BurpProject_FindI32, err error) {
	if (this._f_chunkCount) {
		return this.chunkCount, nil
	}
	this._f_chunkCount = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp22, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp23 := NewBurpProject_FindI32(0, this.Base, tmp22)
	err = tmp23.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunkCount = tmp23
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunkCount, nil
}

/**
 * Zwtw/Zmea chunked collection (Proxy history views, identity buckets).
 */
type BurpProject_ChunkedCollection struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_chunkListAddr bool
	chunkListAddr *BurpProject_FindAddr
	_f_chunkSize bool
	chunkSize *BurpProject_FindI32
	_f_leadingOffset bool
	leadingOffset *BurpProject_FindI32
	_f_size bool
	size *BurpProject_FindI32
}
func NewBurpProject_ChunkedCollection(base int64) *BurpProject_ChunkedCollection {
	return &BurpProject_ChunkedCollection{
		Base: base,
	}
}

func (this BurpProject_ChunkedCollection) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ChunkedCollection) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24 := NewBurpProject_CompactObject(this.Base)
	err = tmp24.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp24
	return err
}
func (this *BurpProject_ChunkedCollection) ChunkListAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_chunkListAddr) {
		return this.chunkListAddr, nil
	}
	this._f_chunkListAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp25, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp26 := NewBurpProject_FindAddr(2, this.Base, tmp25)
	err = tmp26.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunkListAddr = tmp26
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunkListAddr, nil
}
func (this *BurpProject_ChunkedCollection) ChunkSize() (v *BurpProject_FindI32, err error) {
	if (this._f_chunkSize) {
		return this.chunkSize, nil
	}
	this._f_chunkSize = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp27, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp28 := NewBurpProject_FindI32(1, this.Base, tmp27)
	err = tmp28.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunkSize = tmp28
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunkSize, nil
}
func (this *BurpProject_ChunkedCollection) LeadingOffset() (v *BurpProject_FindI32, err error) {
	if (this._f_leadingOffset) {
		return this.leadingOffset, nil
	}
	this._f_leadingOffset = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp29, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp30 := NewBurpProject_FindI32(3, this.Base, tmp29)
	err = tmp30.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.leadingOffset = tmp30
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.leadingOffset, nil
}
func (this *BurpProject_ChunkedCollection) Size() (v *BurpProject_FindI32, err error) {
	if (this._f_size) {
		return this.size, nil
	}
	this._f_size = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp31, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp32 := NewBurpProject_FindI32(0, this.Base, tmp31)
	err = tmp32.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.size = tmp32
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.size, nil
}
type BurpProject_CompactObject struct {
	Flags uint8
	TypeId uint8
	Subtype uint8
	DescriptorCount uint8
	Descriptors []*BurpProject_Descriptor
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_fwdAddr bool
	fwdAddr int64
	_f_isForwarding bool
	isForwarding bool
	_f_tableEnd bool
	tableEnd int64
}
func NewBurpProject_CompactObject(base int64) *BurpProject_CompactObject {
	return &BurpProject_CompactObject{
		Base: base,
	}
}

func (this BurpProject_CompactObject) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_CompactObject) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp33, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flags = tmp33
	tmp34, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TypeId = tmp34
	tmp35, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Subtype = tmp35
	tmp36, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DescriptorCount = tmp36
	if (this.Flags & 1 == 0) {
		for i := 0; i < int(this.DescriptorCount); i++ {
			_ = i
			tmp37 := NewBurpProject_Descriptor()
			err = tmp37.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.Descriptors = append(this.Descriptors, tmp37)
		}
	}
	return err
}
func (this *BurpProject_CompactObject) FwdAddr() (v int64, err error) {
	if (this._f_fwdAddr) {
		return this.fwdAddr, nil
	}
	this._f_fwdAddr = true
	if (this.Flags & 1 != 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return 0, err
		}
		_, err = this._io.Seek(int64(this.Base + 1), io.SeekStart)
		if err != nil {
			return 0, err
		}
		tmp38, err := this._io.ReadS8be()
		if err != nil {
			return 0, err
		}
		this.fwdAddr = tmp38
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return 0, err
		}
	}
	return this.fwdAddr, nil
}
func (this *BurpProject_CompactObject) IsForwarding() (v bool, err error) {
	if (this._f_isForwarding) {
		return this.isForwarding, nil
	}
	this._f_isForwarding = true
	this.isForwarding = bool(this.Flags & 1 != 0)
	return this.isForwarding, nil
}
func (this *BurpProject_CompactObject) TableEnd() (v int64, err error) {
	if (this._f_tableEnd) {
		return this.tableEnd, nil
	}
	this._f_tableEnd = true
	this.tableEnd = int64(int64((this.Base + 4) + int64(this.DescriptorCount) * 3))
	return this.tableEnd, nil
}

/**
 * 3-byte descriptor entry (field id, relative offset from object start).
 */
type BurpProject_Descriptor struct {
	FieldId uint8
	RelativeOffset int16
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject_Descriptor() *BurpProject_Descriptor {
	return &BurpProject_Descriptor{
	}
}

func (this BurpProject_Descriptor) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_Descriptor) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp39, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.FieldId = tmp39
	tmp40, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RelativeOffset = int16(tmp40)
	return err
}

/**
 * Zg_i/Zmex collection; logical size plus one backing address array.
 */
type BurpProject_DirectCollection struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_backingAddr bool
	backingAddr *BurpProject_FindAddr
	_f_size bool
	size *BurpProject_FindI32
}
func NewBurpProject_DirectCollection(base int64) *BurpProject_DirectCollection {
	return &BurpProject_DirectCollection{
		Base: base,
	}
}

func (this BurpProject_DirectCollection) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_DirectCollection) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp41 := NewBurpProject_CompactObject(this.Base)
	err = tmp41.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp41
	return err
}
func (this *BurpProject_DirectCollection) BackingAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_backingAddr) {
		return this.backingAddr, nil
	}
	this._f_backingAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp42, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp43 := NewBurpProject_FindAddr(1, this.Base, tmp42)
	err = tmp43.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.backingAddr = tmp43
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.backingAddr, nil
}
func (this *BurpProject_DirectCollection) Size() (v *BurpProject_FindI32, err error) {
	if (this._f_size) {
		return this.size, nil
	}
	this._f_size = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp44, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp45 := NewBurpProject_FindI32(0, this.Base, tmp44)
	err = tmp45.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.size = tmp45
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.size, nil
}
type BurpProject_FindAddr struct {
	Entry []*BurpProject_Descriptor
	Target uint8
	Base int64
	TableEnd int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_found bool
	found bool
	_f_value bool
	value int64
}
func NewBurpProject_FindAddr(target uint8, base int64, tableEnd int64) *BurpProject_FindAddr {
	return &BurpProject_FindAddr{
		Target: target,
		Base: base,
		TableEnd: tableEnd,
	}
}

func (this BurpProject_FindAddr) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_FindAddr) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 1;; i++ {
		tmp46 := NewBurpProject_Descriptor()
		err = tmp46.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp46
		this.Entry = append(this.Entry, _it)
		tmp47 := this.Entry
		tmp48, err := this._io.Pos()
		if err != nil {
			return err
		}
		if  ((tmp47[len(tmp47) - 1].FieldId == this.Target) || (tmp48 >= this.TableEnd))  {
			break
		}
	}
	return err
}
func (this *BurpProject_FindAddr) Found() (v bool, err error) {
	if (this._f_found) {
		return this.found, nil
	}
	this._f_found = true
	tmp49 := this.Entry
	this.found = bool(tmp49[len(tmp49) - 1].FieldId == this.Target)
	return this.found, nil
}
func (this *BurpProject_FindAddr) Value() (v int64, err error) {
	if (this._f_value) {
		return this.value, nil
	}
	this._f_value = true
	tmp50 := this.Entry
	if (tmp50[len(tmp50) - 1].FieldId == this.Target) {
		_pos, err := this._io.Pos()
		if err != nil {
			return 0, err
		}
		tmp51 := this.Entry
		_, err = this._io.Seek(int64(this.Base + int64(tmp51[len(tmp51) - 1].RelativeOffset)), io.SeekStart)
		if err != nil {
			return 0, err
		}
		tmp52, err := this._io.ReadS8be()
		if err != nil {
			return 0, err
		}
		this.value = tmp52
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return 0, err
		}
	}
	return this.value, nil
}
type BurpProject_FindI32 struct {
	Entry []*BurpProject_Descriptor
	Target uint8
	Base int64
	TableEnd int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_found bool
	found bool
	_f_value bool
	value int32
}
func NewBurpProject_FindI32(target uint8, base int64, tableEnd int64) *BurpProject_FindI32 {
	return &BurpProject_FindI32{
		Target: target,
		Base: base,
		TableEnd: tableEnd,
	}
}

func (this BurpProject_FindI32) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_FindI32) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 1;; i++ {
		tmp53 := NewBurpProject_Descriptor()
		err = tmp53.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp53
		this.Entry = append(this.Entry, _it)
		tmp54 := this.Entry
		tmp55, err := this._io.Pos()
		if err != nil {
			return err
		}
		if  ((tmp54[len(tmp54) - 1].FieldId == this.Target) || (tmp55 >= this.TableEnd))  {
			break
		}
	}
	return err
}
func (this *BurpProject_FindI32) Found() (v bool, err error) {
	if (this._f_found) {
		return this.found, nil
	}
	this._f_found = true
	tmp56 := this.Entry
	this.found = bool(tmp56[len(tmp56) - 1].FieldId == this.Target)
	return this.found, nil
}
func (this *BurpProject_FindI32) Value() (v int32, err error) {
	if (this._f_value) {
		return this.value, nil
	}
	this._f_value = true
	tmp57 := this.Entry
	if (tmp57[len(tmp57) - 1].FieldId == this.Target) {
		_pos, err := this._io.Pos()
		if err != nil {
			return 0, err
		}
		tmp58 := this.Entry
		_, err = this._io.Seek(int64(this.Base + int64(tmp58[len(tmp58) - 1].RelativeOffset)), io.SeekStart)
		if err != nil {
			return 0, err
		}
		tmp59, err := this._io.ReadS4be()
		if err != nil {
			return 0, err
		}
		this.value = tmp59
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return 0, err
		}
	}
	return this.value, nil
}
type BurpProject_FindU64 struct {
	Entry []*BurpProject_Descriptor
	Target uint8
	Base int64
	TableEnd int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent *BurpProject_UuidObj
	_f_found bool
	found bool
	_f_value bool
	value uint64
}
func NewBurpProject_FindU64(target uint8, base int64, tableEnd int64) *BurpProject_FindU64 {
	return &BurpProject_FindU64{
		Target: target,
		Base: base,
		TableEnd: tableEnd,
	}
}

func (this BurpProject_FindU64) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_FindU64) Read(io *kaitai.Stream, parent *BurpProject_UuidObj, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 1;; i++ {
		tmp60 := NewBurpProject_Descriptor()
		err = tmp60.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp60
		this.Entry = append(this.Entry, _it)
		tmp61 := this.Entry
		tmp62, err := this._io.Pos()
		if err != nil {
			return err
		}
		if  ((tmp61[len(tmp61) - 1].FieldId == this.Target) || (tmp62 >= this.TableEnd))  {
			break
		}
	}
	return err
}
func (this *BurpProject_FindU64) Found() (v bool, err error) {
	if (this._f_found) {
		return this.found, nil
	}
	this._f_found = true
	tmp63 := this.Entry
	this.found = bool(tmp63[len(tmp63) - 1].FieldId == this.Target)
	return this.found, nil
}
func (this *BurpProject_FindU64) Value() (v uint64, err error) {
	if (this._f_value) {
		return this.value, nil
	}
	this._f_value = true
	tmp64 := this.Entry
	if (tmp64[len(tmp64) - 1].FieldId == this.Target) {
		_pos, err := this._io.Pos()
		if err != nil {
			return 0, err
		}
		tmp65 := this.Entry
		_, err = this._io.Seek(int64(this.Base + int64(tmp65[len(tmp65) - 1].RelativeOffset)), io.SeekStart)
		if err != nil {
			return 0, err
		}
		tmp66, err := this._io.ReadU8be()
		if err != nil {
			return 0, err
		}
		this.value = tmp66
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return 0, err
		}
	}
	return this.value, nil
}
type BurpProject_FindU8 struct {
	Entry []*BurpProject_Descriptor
	Target uint8
	Base int64
	TableEnd int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent *BurpProject_RepeaterGroup
	_f_found bool
	found bool
	_f_value bool
	value uint8
}
func NewBurpProject_FindU8(target uint8, base int64, tableEnd int64) *BurpProject_FindU8 {
	return &BurpProject_FindU8{
		Target: target,
		Base: base,
		TableEnd: tableEnd,
	}
}

func (this BurpProject_FindU8) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_FindU8) Read(io *kaitai.Stream, parent *BurpProject_RepeaterGroup, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 1;; i++ {
		tmp67 := NewBurpProject_Descriptor()
		err = tmp67.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp67
		this.Entry = append(this.Entry, _it)
		tmp68 := this.Entry
		tmp69, err := this._io.Pos()
		if err != nil {
			return err
		}
		if  ((tmp68[len(tmp68) - 1].FieldId == this.Target) || (tmp69 >= this.TableEnd))  {
			break
		}
	}
	return err
}
func (this *BurpProject_FindU8) Found() (v bool, err error) {
	if (this._f_found) {
		return this.found, nil
	}
	this._f_found = true
	tmp70 := this.Entry
	this.found = bool(tmp70[len(tmp70) - 1].FieldId == this.Target)
	return this.found, nil
}
func (this *BurpProject_FindU8) Value() (v uint8, err error) {
	if (this._f_value) {
		return this.value, nil
	}
	this._f_value = true
	tmp71 := this.Entry
	if (tmp71[len(tmp71) - 1].FieldId == this.Target) {
		_pos, err := this._io.Pos()
		if err != nil {
			return 0, err
		}
		tmp72 := this.Entry
		_, err = this._io.Seek(int64(this.Base + int64(tmp72[len(tmp72) - 1].RelativeOffset)), io.SeekStart)
		if err != nil {
			return 0, err
		}
		tmp73, err := this._io.ReadU1()
		if err != nil {
			return 0, err
		}
		this.value = tmp73
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return 0, err
		}
	}
	return this.value, nil
}

/**
 * 72-byte big-endian outer header.
 */
type BurpProject_Header struct {
	Magic []byte
	OuterVersion int32
	Compatibility int32
	SchemaFloor uint16
	SchemaCurrent uint16
	RandomIdentifier uint32
	Reserved []byte
	MetadataRoot int64
	SegmentSpan int64
	AllocationCursor int64
	ProjectRoot int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent *BurpProject
}
func NewBurpProject_Header() *BurpProject_Header {
	return &BurpProject_Header{
	}
}

func (this BurpProject_Header) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_Header) Read(io *kaitai.Stream, parent *BurpProject, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp74, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp74 = tmp74
	this.Magic = tmp74
	if !(bytes.Equal(this.Magic, []uint8{102, 133, 130, 128})) {
		return kaitai.NewValidationNotEqualError([]uint8{102, 133, 130, 128}, this.Magic, this._io, "/types/header/seq/0")
	}
	tmp75, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.OuterVersion = int32(tmp75)
	tmp76, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.Compatibility = int32(tmp76)
	tmp77, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SchemaFloor = uint16(tmp77)
	tmp78, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SchemaCurrent = uint16(tmp78)
	tmp79, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RandomIdentifier = uint32(tmp79)
	tmp80, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp80 = tmp80
	this.Reserved = tmp80
	tmp81, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.MetadataRoot = int64(tmp81)
	tmp82, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.SegmentSpan = int64(tmp82)
	tmp83, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.AllocationCursor = int64(tmp83)
	tmp84, err := this._io.ReadS8be()
	if err != nil {
		return err
	}
	this.ProjectRoot = int64(tmp84)
	return err
}

/**
 * Zpt2 identity index; field 2 expected size, field 3 bucket collection.
 */
type BurpProject_IdentityIndex struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_bucketsAddr bool
	bucketsAddr *BurpProject_FindAddr
	_f_expectedSize bool
	expectedSize *BurpProject_FindI32
}
func NewBurpProject_IdentityIndex(base int64) *BurpProject_IdentityIndex {
	return &BurpProject_IdentityIndex{
		Base: base,
	}
}

func (this BurpProject_IdentityIndex) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_IdentityIndex) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp85 := NewBurpProject_CompactObject(this.Base)
	err = tmp85.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp85
	return err
}
func (this *BurpProject_IdentityIndex) BucketsAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_bucketsAddr) {
		return this.bucketsAddr, nil
	}
	this._f_bucketsAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp86, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp87 := NewBurpProject_FindAddr(3, this.Base, tmp86)
	err = tmp87.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.bucketsAddr = tmp87
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.bucketsAddr, nil
}
func (this *BurpProject_IdentityIndex) ExpectedSize() (v *BurpProject_FindI32, err error) {
	if (this._f_expectedSize) {
		return this.expectedSize, nil
	}
	this._f_expectedSize = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp88, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp89 := NewBurpProject_FindI32(2, this.Base, tmp88)
	err = tmp89.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.expectedSize = tmp89
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.expectedSize, nil
}

/**
 * Zv1/Zmju immutable string; field 0 points at a UTF-16BE char array.
 */
type BurpProject_ImmutableString struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_charsAddr bool
	charsAddr *BurpProject_FindAddr
}
func NewBurpProject_ImmutableString(base int64) *BurpProject_ImmutableString {
	return &BurpProject_ImmutableString{
		Base: base,
	}
}

func (this BurpProject_ImmutableString) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ImmutableString) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp90 := NewBurpProject_CompactObject(this.Base)
	err = tmp90.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp90
	return err
}
func (this *BurpProject_ImmutableString) CharsAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_charsAddr) {
		return this.charsAddr, nil
	}
	this._f_charsAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp91, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp92 := NewBurpProject_FindAddr(0, this.Base, tmp91)
	err = tmp92.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.charsAddr = tmp92
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.charsAddr, nil
}

/**
 * Zvp/Zmjj chunked mutable string (Repeater captions).
 */
type BurpProject_MutableString struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_chunkWidth bool
	chunkWidth *BurpProject_FindI32
	_f_chunksAddr bool
	chunksAddr *BurpProject_FindAddr
	_f_length bool
	length *BurpProject_FindI32
}
func NewBurpProject_MutableString(base int64) *BurpProject_MutableString {
	return &BurpProject_MutableString{
		Base: base,
	}
}

func (this BurpProject_MutableString) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_MutableString) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp93 := NewBurpProject_CompactObject(this.Base)
	err = tmp93.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp93
	return err
}
func (this *BurpProject_MutableString) ChunkWidth() (v *BurpProject_FindI32, err error) {
	if (this._f_chunkWidth) {
		return this.chunkWidth, nil
	}
	this._f_chunkWidth = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp94, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp95 := NewBurpProject_FindI32(2, this.Base, tmp94)
	err = tmp95.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunkWidth = tmp95
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunkWidth, nil
}
func (this *BurpProject_MutableString) ChunksAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_chunksAddr) {
		return this.chunksAddr, nil
	}
	this._f_chunksAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp96, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp97 := NewBurpProject_FindAddr(3, this.Base, tmp96)
	err = tmp97.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.chunksAddr = tmp97
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.chunksAddr, nil
}
func (this *BurpProject_MutableString) Length() (v *BurpProject_FindI32, err error) {
	if (this._f_length) {
		return this.length, nil
	}
	this._f_length = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp98, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp99 := NewBurpProject_FindI32(0, this.Base, tmp98)
	err = tmp99.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.length = tmp99
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.length, nil
}

/**
 * Schema-226/227 project root.
 */
type BurpProject_ProjectRoot struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_installId bool
	installId *BurpProject_FindAddr
	_f_projectIdentifier bool
	projectIdentifier *BurpProject_FindAddr
	_f_projectName bool
	projectName *BurpProject_FindAddr
	_f_proxyRootAddr bool
	proxyRootAddr *BurpProject_FindAddr
	_f_repeaterRootAddr bool
	repeaterRootAddr *BurpProject_FindAddr
	_f_targetRootAddr bool
	targetRootAddr *BurpProject_FindAddr
}
func NewBurpProject_ProjectRoot(base int64) *BurpProject_ProjectRoot {
	return &BurpProject_ProjectRoot{
		Base: base,
	}
}

func (this BurpProject_ProjectRoot) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ProjectRoot) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp100 := NewBurpProject_CompactObject(this.Base)
	err = tmp100.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp100
	return err
}
func (this *BurpProject_ProjectRoot) InstallId() (v *BurpProject_FindAddr, err error) {
	if (this._f_installId) {
		return this.installId, nil
	}
	this._f_installId = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp101, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp102 := NewBurpProject_FindAddr(0, this.Base, tmp101)
	err = tmp102.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.installId = tmp102
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.installId, nil
}
func (this *BurpProject_ProjectRoot) ProjectIdentifier() (v *BurpProject_FindAddr, err error) {
	if (this._f_projectIdentifier) {
		return this.projectIdentifier, nil
	}
	this._f_projectIdentifier = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp103, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp104 := NewBurpProject_FindAddr(15, this.Base, tmp103)
	err = tmp104.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.projectIdentifier = tmp104
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.projectIdentifier, nil
}
func (this *BurpProject_ProjectRoot) ProjectName() (v *BurpProject_FindAddr, err error) {
	if (this._f_projectName) {
		return this.projectName, nil
	}
	this._f_projectName = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp105, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp106 := NewBurpProject_FindAddr(6, this.Base, tmp105)
	err = tmp106.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.projectName = tmp106
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.projectName, nil
}
func (this *BurpProject_ProjectRoot) ProxyRootAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_proxyRootAddr) {
		return this.proxyRootAddr, nil
	}
	this._f_proxyRootAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp107, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp108 := NewBurpProject_FindAddr(1, this.Base, tmp107)
	err = tmp108.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.proxyRootAddr = tmp108
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.proxyRootAddr, nil
}
func (this *BurpProject_ProjectRoot) RepeaterRootAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_repeaterRootAddr) {
		return this.repeaterRootAddr, nil
	}
	this._f_repeaterRootAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp109, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp110 := NewBurpProject_FindAddr(2, this.Base, tmp109)
	err = tmp110.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.repeaterRootAddr = tmp110
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.repeaterRootAddr, nil
}
func (this *BurpProject_ProjectRoot) TargetRootAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_targetRootAddr) {
		return this.targetRootAddr, nil
	}
	this._f_targetRootAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp111, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp112 := NewBurpProject_FindAddr(3, this.Base, tmp111)
	err = tmp112.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.targetRootAddr = tmp112
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.targetRootAddr, nil
}

/**
 * Proxy history item Zp1u (descriptor Zdr); 15/18 are the raw exchange.
 */
type BurpProject_ProxyItem struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_requestAddr bool
	requestAddr *BurpProject_FindAddr
	_f_requestAlt1Addr bool
	requestAlt1Addr *BurpProject_FindAddr
	_f_requestAlt2Addr bool
	requestAlt2Addr *BurpProject_FindAddr
	_f_responseAddr bool
	responseAddr *BurpProject_FindAddr
	_f_responseAlt1Addr bool
	responseAlt1Addr *BurpProject_FindAddr
	_f_responseAlt2Addr bool
	responseAlt2Addr *BurpProject_FindAddr
}
func NewBurpProject_ProxyItem(base int64) *BurpProject_ProxyItem {
	return &BurpProject_ProxyItem{
		Base: base,
	}
}

func (this BurpProject_ProxyItem) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ProxyItem) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp113 := NewBurpProject_CompactObject(this.Base)
	err = tmp113.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp113
	return err
}
func (this *BurpProject_ProxyItem) RequestAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_requestAddr) {
		return this.requestAddr, nil
	}
	this._f_requestAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp114, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp115 := NewBurpProject_FindAddr(15, this.Base, tmp114)
	err = tmp115.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.requestAddr = tmp115
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.requestAddr, nil
}
func (this *BurpProject_ProxyItem) RequestAlt1Addr() (v *BurpProject_FindAddr, err error) {
	if (this._f_requestAlt1Addr) {
		return this.requestAlt1Addr, nil
	}
	this._f_requestAlt1Addr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp116, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp117 := NewBurpProject_FindAddr(16, this.Base, tmp116)
	err = tmp117.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.requestAlt1Addr = tmp117
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.requestAlt1Addr, nil
}
func (this *BurpProject_ProxyItem) RequestAlt2Addr() (v *BurpProject_FindAddr, err error) {
	if (this._f_requestAlt2Addr) {
		return this.requestAlt2Addr, nil
	}
	this._f_requestAlt2Addr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp118, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp119 := NewBurpProject_FindAddr(17, this.Base, tmp118)
	err = tmp119.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.requestAlt2Addr = tmp119
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.requestAlt2Addr, nil
}
func (this *BurpProject_ProxyItem) ResponseAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_responseAddr) {
		return this.responseAddr, nil
	}
	this._f_responseAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp120, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp121 := NewBurpProject_FindAddr(18, this.Base, tmp120)
	err = tmp121.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.responseAddr = tmp121
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.responseAddr, nil
}
func (this *BurpProject_ProxyItem) ResponseAlt1Addr() (v *BurpProject_FindAddr, err error) {
	if (this._f_responseAlt1Addr) {
		return this.responseAlt1Addr, nil
	}
	this._f_responseAlt1Addr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp122, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp123 := NewBurpProject_FindAddr(19, this.Base, tmp122)
	err = tmp123.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.responseAlt1Addr = tmp123
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.responseAlt1Addr, nil
}
func (this *BurpProject_ProxyItem) ResponseAlt2Addr() (v *BurpProject_FindAddr, err error) {
	if (this._f_responseAlt2Addr) {
		return this.responseAlt2Addr, nil
	}
	this._f_responseAlt2Addr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp124, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp125 := NewBurpProject_FindAddr(20, this.Base, tmp124)
	err = tmp125.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.responseAlt2Addr = tmp125
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.responseAlt2Addr, nil
}

/**
 * Proxy root Zkx; fields 0 and 1 are chunked history views.
 */
type BurpProject_ProxyRoot struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_historyAllAddr bool
	historyAllAddr *BurpProject_FindAddr
	_f_historyUniqueAddr bool
	historyUniqueAddr *BurpProject_FindAddr
}
func NewBurpProject_ProxyRoot(base int64) *BurpProject_ProxyRoot {
	return &BurpProject_ProxyRoot{
		Base: base,
	}
}

func (this BurpProject_ProxyRoot) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_ProxyRoot) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp126 := NewBurpProject_CompactObject(this.Base)
	err = tmp126.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp126
	return err
}
func (this *BurpProject_ProxyRoot) HistoryAllAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_historyAllAddr) {
		return this.historyAllAddr, nil
	}
	this._f_historyAllAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp127, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp128 := NewBurpProject_FindAddr(0, this.Base, tmp127)
	err = tmp128.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.historyAllAddr = tmp128
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.historyAllAddr, nil
}
func (this *BurpProject_ProxyRoot) HistoryUniqueAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_historyUniqueAddr) {
		return this.historyUniqueAddr, nil
	}
	this._f_historyUniqueAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp129, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp130 := NewBurpProject_FindAddr(1, this.Base, tmp129)
	err = tmp130.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.historyUniqueAddr = tmp130
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.historyUniqueAddr, nil
}

/**
 * Repeater tab group.
 */
type BurpProject_RepeaterGroup struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_colorId bool
	colorId *BurpProject_FindU8
	_f_expanded bool
	expanded *BurpProject_FindU8
	_f_index bool
	index *BurpProject_FindI32
	_f_nameAddr bool
	nameAddr *BurpProject_FindAddr
	_f_uuidAddr bool
	uuidAddr *BurpProject_FindAddr
}
func NewBurpProject_RepeaterGroup(base int64) *BurpProject_RepeaterGroup {
	return &BurpProject_RepeaterGroup{
		Base: base,
	}
}

func (this BurpProject_RepeaterGroup) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_RepeaterGroup) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp131 := NewBurpProject_CompactObject(this.Base)
	err = tmp131.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp131
	return err
}
func (this *BurpProject_RepeaterGroup) ColorId() (v *BurpProject_FindU8, err error) {
	if (this._f_colorId) {
		return this.colorId, nil
	}
	this._f_colorId = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp132, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp133 := NewBurpProject_FindU8(1, this.Base, tmp132)
	err = tmp133.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.colorId = tmp133
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.colorId, nil
}
func (this *BurpProject_RepeaterGroup) Expanded() (v *BurpProject_FindU8, err error) {
	if (this._f_expanded) {
		return this.expanded, nil
	}
	this._f_expanded = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp134, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp135 := NewBurpProject_FindU8(2, this.Base, tmp134)
	err = tmp135.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.expanded = tmp135
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.expanded, nil
}
func (this *BurpProject_RepeaterGroup) Index() (v *BurpProject_FindI32, err error) {
	if (this._f_index) {
		return this.index, nil
	}
	this._f_index = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp136, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp137 := NewBurpProject_FindI32(3, this.Base, tmp136)
	err = tmp137.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.index = tmp137
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.index, nil
}
func (this *BurpProject_RepeaterGroup) NameAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_nameAddr) {
		return this.nameAddr, nil
	}
	this._f_nameAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp138, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp139 := NewBurpProject_FindAddr(0, this.Base, tmp138)
	err = tmp139.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.nameAddr = tmp139
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.nameAddr, nil
}
func (this *BurpProject_RepeaterGroup) UuidAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_uuidAddr) {
		return this.uuidAddr, nil
	}
	this._f_uuidAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp140, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp141 := NewBurpProject_FindAddr(4, this.Base, tmp140)
	err = tmp141.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.uuidAddr = tmp141
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.uuidAddr, nil
}

/**
 * Zx4g message pair (descriptor Zdg); fields 2/3 are raw request/response.
 */
type BurpProject_RepeaterPair struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_requestAddr bool
	requestAddr *BurpProject_FindAddr
	_f_responseAddr bool
	responseAddr *BurpProject_FindAddr
}
func NewBurpProject_RepeaterPair(base int64) *BurpProject_RepeaterPair {
	return &BurpProject_RepeaterPair{
		Base: base,
	}
}

func (this BurpProject_RepeaterPair) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_RepeaterPair) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp142 := NewBurpProject_CompactObject(this.Base)
	err = tmp142.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp142
	return err
}
func (this *BurpProject_RepeaterPair) RequestAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_requestAddr) {
		return this.requestAddr, nil
	}
	this._f_requestAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp143, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp144 := NewBurpProject_FindAddr(2, this.Base, tmp143)
	err = tmp144.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.requestAddr = tmp144
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.requestAddr, nil
}
func (this *BurpProject_RepeaterPair) ResponseAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_responseAddr) {
		return this.responseAddr, nil
	}
	this._f_responseAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp145, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp146 := NewBurpProject_FindAddr(3, this.Base, tmp145)
	err = tmp146.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.responseAddr = tmp146
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.responseAddr, nil
}

/**
 * Repeater root; field 1 tabs, field 4 groups (direct collections).
 */
type BurpProject_RepeaterRoot struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_groupsAddr bool
	groupsAddr *BurpProject_FindAddr
	_f_tabsAddr bool
	tabsAddr *BurpProject_FindAddr
}
func NewBurpProject_RepeaterRoot(base int64) *BurpProject_RepeaterRoot {
	return &BurpProject_RepeaterRoot{
		Base: base,
	}
}

func (this BurpProject_RepeaterRoot) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_RepeaterRoot) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp147 := NewBurpProject_CompactObject(this.Base)
	err = tmp147.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp147
	return err
}
func (this *BurpProject_RepeaterRoot) GroupsAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_groupsAddr) {
		return this.groupsAddr, nil
	}
	this._f_groupsAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp148, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp149 := NewBurpProject_FindAddr(4, this.Base, tmp148)
	err = tmp149.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.groupsAddr = tmp149
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.groupsAddr, nil
}
func (this *BurpProject_RepeaterRoot) TabsAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_tabsAddr) {
		return this.tabsAddr, nil
	}
	this._f_tabsAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp150, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp151 := NewBurpProject_FindAddr(1, this.Base, tmp150)
	err = tmp151.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.tabsAddr = tmp151
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.tabsAddr, nil
}

/**
 * Repeater tab (caption field 0, pairs field 2, current request field 4).
 */
type BurpProject_RepeaterTab struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_captionAddr bool
	captionAddr *BurpProject_FindAddr
	_f_currentRequestAddr bool
	currentRequestAddr *BurpProject_FindAddr
	_f_groupAddr bool
	groupAddr *BurpProject_FindAddr
	_f_pairsAddr bool
	pairsAddr *BurpProject_FindAddr
	_f_uuidAddr bool
	uuidAddr *BurpProject_FindAddr
}
func NewBurpProject_RepeaterTab(base int64) *BurpProject_RepeaterTab {
	return &BurpProject_RepeaterTab{
		Base: base,
	}
}

func (this BurpProject_RepeaterTab) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_RepeaterTab) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp152 := NewBurpProject_CompactObject(this.Base)
	err = tmp152.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp152
	return err
}
func (this *BurpProject_RepeaterTab) CaptionAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_captionAddr) {
		return this.captionAddr, nil
	}
	this._f_captionAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp153, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp154 := NewBurpProject_FindAddr(0, this.Base, tmp153)
	err = tmp154.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.captionAddr = tmp154
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.captionAddr, nil
}
func (this *BurpProject_RepeaterTab) CurrentRequestAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_currentRequestAddr) {
		return this.currentRequestAddr, nil
	}
	this._f_currentRequestAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp155, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp156 := NewBurpProject_FindAddr(4, this.Base, tmp155)
	err = tmp156.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.currentRequestAddr = tmp156
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.currentRequestAddr, nil
}
func (this *BurpProject_RepeaterTab) GroupAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_groupAddr) {
		return this.groupAddr, nil
	}
	this._f_groupAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp157, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp158 := NewBurpProject_FindAddr(32, this.Base, tmp157)
	err = tmp158.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.groupAddr = tmp158
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.groupAddr, nil
}
func (this *BurpProject_RepeaterTab) PairsAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_pairsAddr) {
		return this.pairsAddr, nil
	}
	this._f_pairsAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp159, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp160 := NewBurpProject_FindAddr(2, this.Base, tmp159)
	err = tmp160.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.pairsAddr = tmp160
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.pairsAddr, nil
}
func (this *BurpProject_RepeaterTab) UuidAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_uuidAddr) {
		return this.uuidAddr, nil
	}
	this._f_uuidAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp161, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp162 := NewBurpProject_FindAddr(33, this.Base, tmp161)
	err = tmp162.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.uuidAddr = tmp162
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.uuidAddr, nil
}
type BurpProject_Roots struct {
	_io *kaitai.Stream
	_root *BurpProject
	_parent *BurpProject
	_f_metadataRootObj bool
	metadataRootObj *BurpProject_CompactObject
	_f_projectRootObj bool
	projectRootObj *BurpProject_CompactObject
}
func NewBurpProject_Roots() *BurpProject_Roots {
	return &BurpProject_Roots{
	}
}

func (this BurpProject_Roots) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_Roots) Read(io *kaitai.Stream, parent *BurpProject, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

/**
 * Object at header metadata root (string chunk recycling pool).
 */
func (this *BurpProject_Roots) MetadataRootObj() (v *BurpProject_CompactObject, err error) {
	if (this._f_metadataRootObj) {
		return this.metadataRootObj, nil
	}
	this._f_metadataRootObj = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.Header.MetadataRoot), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp163 := NewBurpProject_CompactObject(this._root.Header.MetadataRoot)
	err = tmp163.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.metadataRootObj = tmp163
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.metadataRootObj, nil
}

/**
 * Compact object at header project root (follow forwarding via nav layer).
 */
func (this *BurpProject_Roots) ProjectRootObj() (v *BurpProject_CompactObject, err error) {
	if (this._f_projectRootObj) {
		return this.projectRootObj, nil
	}
	this._f_projectRootObj = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.Header.ProjectRoot), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp164 := NewBurpProject_CompactObject(this._root.Header.ProjectRoot)
	err = tmp164.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.projectRootObj = tmp164
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.projectRootObj, nil
}

/**
 * Zfkk message metadata (descriptor Zkp); fields 0/1 raw request/response.
 */
type BurpProject_SiteMessage struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_requestAddr bool
	requestAddr *BurpProject_FindAddr
	_f_responseAddr bool
	responseAddr *BurpProject_FindAddr
}
func NewBurpProject_SiteMessage(base int64) *BurpProject_SiteMessage {
	return &BurpProject_SiteMessage{
		Base: base,
	}
}

func (this BurpProject_SiteMessage) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_SiteMessage) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp165 := NewBurpProject_CompactObject(this.Base)
	err = tmp165.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp165
	return err
}
func (this *BurpProject_SiteMessage) RequestAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_requestAddr) {
		return this.requestAddr, nil
	}
	this._f_requestAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp166, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp167 := NewBurpProject_FindAddr(0, this.Base, tmp166)
	err = tmp167.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.requestAddr = tmp167
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.requestAddr, nil
}
func (this *BurpProject_SiteMessage) ResponseAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_responseAddr) {
		return this.responseAddr, nil
	}
	this._f_responseAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp168, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp169 := NewBurpProject_FindAddr(1, this.Base, tmp168)
	err = tmp169.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.responseAddr = tmp169
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.responseAddr, nil
}

/**
 * Site Map hierarchy node; field 33 references message metadata Zfkk.
 */
type BurpProject_TargetNode struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_messageAddr bool
	messageAddr *BurpProject_FindAddr
}
func NewBurpProject_TargetNode(base int64) *BurpProject_TargetNode {
	return &BurpProject_TargetNode{
		Base: base,
	}
}

func (this BurpProject_TargetNode) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_TargetNode) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp170 := NewBurpProject_CompactObject(this.Base)
	err = tmp170.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp170
	return err
}
func (this *BurpProject_TargetNode) MessageAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_messageAddr) {
		return this.messageAddr, nil
	}
	this._f_messageAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp171, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp172 := NewBurpProject_FindAddr(33, this.Base, tmp171)
	err = tmp172.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.messageAddr = tmp172
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.messageAddr, nil
}

/**
 * Shared Target/Scanner indexes Zg70; field 3 is the identity index.
 */
type BurpProject_TargetRoot struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_identityIndexAddr bool
	identityIndexAddr *BurpProject_FindAddr
}
func NewBurpProject_TargetRoot(base int64) *BurpProject_TargetRoot {
	return &BurpProject_TargetRoot{
		Base: base,
	}
}

func (this BurpProject_TargetRoot) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_TargetRoot) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp173 := NewBurpProject_CompactObject(this.Base)
	err = tmp173.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp173
	return err
}
func (this *BurpProject_TargetRoot) IdentityIndexAddr() (v *BurpProject_FindAddr, err error) {
	if (this._f_identityIndexAddr) {
		return this.identityIndexAddr, nil
	}
	this._f_identityIndexAddr = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp174, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp175 := NewBurpProject_FindAddr(3, this.Base, tmp174)
	err = tmp175.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.identityIndexAddr = tmp175
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.identityIndexAddr, nil
}

/**
 * Variable array of UTF-16BE code units (string character storage).
 */
type BurpProject_Utf16Array struct {
	TotalSize int32
	CharCount int32
	Data []byte
	Padding []byte
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject_Utf16Array() *BurpProject_Utf16Array {
	return &BurpProject_Utf16Array{
	}
}

func (this BurpProject_Utf16Array) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_Utf16Array) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp176, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.TotalSize = int32(tmp176)
	tmp177, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.CharCount = int32(tmp177)
	tmp178, err := this._io.ReadBytes(int(this.CharCount * 2))
	if err != nil {
		return err
	}
	tmp178 = tmp178
	this.Data = tmp178
	if (this.CharCount == 0) {
		tmp179, err := this._io.ReadBytes(int(1))
		if err != nil {
			return err
		}
		tmp179 = tmp179
		this.Padding = tmp179
	}
	return err
}

/**
 * Two-long UUID object (Repeater tabs and groups).
 */
type BurpProject_UuidObj struct {
	Obj *BurpProject_CompactObject
	Base int64
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
	_f_high bool
	high *BurpProject_FindU64
	_f_low bool
	low *BurpProject_FindU64
}
func NewBurpProject_UuidObj(base int64) *BurpProject_UuidObj {
	return &BurpProject_UuidObj{
		Base: base,
	}
}

func (this BurpProject_UuidObj) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_UuidObj) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp180 := NewBurpProject_CompactObject(this.Base)
	err = tmp180.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Obj = tmp180
	return err
}
func (this *BurpProject_UuidObj) High() (v *BurpProject_FindU64, err error) {
	if (this._f_high) {
		return this.high, nil
	}
	this._f_high = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp181, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp182 := NewBurpProject_FindU64(0, this.Base, tmp181)
	err = tmp182.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.high = tmp182
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.high, nil
}
func (this *BurpProject_UuidObj) Low() (v *BurpProject_FindU64, err error) {
	if (this._f_low) {
		return this.low, nil
	}
	this._f_low = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Base + 4), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp183, err := this.Obj.TableEnd()
	if err != nil {
		return nil, err
	}
	tmp184 := NewBurpProject_FindU64(1, this.Base, tmp183)
	err = tmp184.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.low = tmp184
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.low, nil
}
type BurpProject_VarRecord struct {
	TotalSize int32
	LogicalLength int32
	Data []byte
	Padding []byte
	_io *kaitai.Stream
	_root *BurpProject
	_parent kaitai.Struct
}
func NewBurpProject_VarRecord() *BurpProject_VarRecord {
	return &BurpProject_VarRecord{
	}
}

func (this BurpProject_VarRecord) IO_() *kaitai.Stream {
	return this._io
}

func (this *BurpProject_VarRecord) Read(io *kaitai.Stream, parent kaitai.Struct, root *BurpProject) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp185, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.TotalSize = int32(tmp185)
	tmp186, err := this._io.ReadS4be()
	if err != nil {
		return err
	}
	this.LogicalLength = int32(tmp186)
	tmp187, err := this._io.ReadBytes(int(this.LogicalLength))
	if err != nil {
		return err
	}
	tmp187 = tmp187
	this.Data = tmp187
	if (this.LogicalLength == 0) {
		tmp188, err := this._io.ReadBytes(int(1))
		if err != nil {
			return err
		}
		tmp188 = tmp188
		this.Padding = tmp188
	}
	return err
}
